set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim'
Plugin 'sickill/vim-monokai'
Plugin 'bronson/vim-visual-star-search'
Plugin 'klen/python-mode'
Plugin 'tpope/vim-fugitive'
Plugin 'itchyny/lightline.vim'

call vundle#end()

set relativenumber
set cursorline      " highlight current line
set laststatus=2    " always show the statusline
set noswapfile      " no .swp files
set encoding=utf-8
setglobal fileencoding=utf-8
set fileencodings=ucs-bom,utf-8,latin1

" excludes cache/vendor directories
let g:ctrlp_custom_ignore = '\v[\/]src/cache|src/app/cache|vendors|node_modules|bower_components|__pycache__|\.pyc$'
let g:ctrlp_working_path_mode = ''

" ipdb shortcut
ab ipdb import ipdb; ipdb.set_trace()  # DEBUG

let NERDTreeIgnore = ['__pycache__', '\.pyc$']

let mapleader = ","
let g:mapleader = ","
map th  :tabfirst<CR>
map tj  :tabnext<CR>
map tk  :tabprev<CR>
map tl  :tablast<CR>
map tt  :tabedit<Space>
map tn  :tabnew<Space>
map tm  :tabm<Space>

"nerdtree
map <leader>n :NERDTreeToggle<CR>
"ack
map <leader>k :Ack!

set nocompatible
set tabstop=4
set shiftwidth=4
set expandtab

set backspace=indent,eol,start
set incsearch
set hlsearch
set autoindent

syntax on

map <C-L> :noh<CR>:redraw!<CR>

" colorscheme
syntax enable
colorscheme monokai

" python-mode
let g:pymode_rope = 0
let g:pymode_options_max_line_length = 180
let g:pymode_lint_options_pep8 = {'max_line_length': 180}
let g:pymode_indent = 1
let g:pymode_folding = 1

" vim-fugitive vertical diff
set diffopt+=vertical

" Status line with lightline
set laststatus=2
set noshowmode
let g:lightline={ 'colorscheme': 'solarized' }
